# Copyright 2026 ImgSurf contributors
# Licensed under the Apache License, Version 2.0
"""Replayable v4-style ImgSurf multi-turn rollout.

Unlike the old implementation, recursive localization is generated by the
policy inside the returned trajectory.  ``response_mask`` selects whether the
inner localization tokens also receive policy gradients.
"""

import copy
import json
import logging
import re
from typing import Any
from uuid import uuid4

import numpy as np
from PIL import Image

from recipe.imgsurf.prompt_utils import (
    USER_PROMPT_STEP10_NO_CROPS,
    build_final_user_text,
    build_refine_user_text,
    render_imgsurf_chat_prompt,
)
from verl.experimental.agent_loop.agent_loop import AgentLoopOutput, AgentLoopWorker, register
from verl.experimental.agent_loop.tool_agent_loop import ToolAgentLoop
from verl.utils.profiler import simple_timer
from verl.utils.rollout_trace import rollout_trace_op

logger = logging.getLogger(__name__)


def _extract_think(text: str) -> str:
    blocks = re.findall(r"<think>\s*(.*?)\s*</think>", text, flags=re.DOTALL | re.IGNORECASE)
    return blocks[-1].strip() if blocks else ""


def _images_from_response(response) -> list[Image.Image]:
    images = response.image or []
    return list(images) if isinstance(images, list) else [images]


@register("imgsurf_tool_agent")
class ImgSurfToolAgentLoop(ToolAgentLoop):
    """Generate initial localization, v4 refinements and the final answer."""

    @classmethod
    def init_class(cls, config, tokenizer, processor, **kwargs):
        if cls._class_initialized:
            return
        super().init_class(config, tokenizer, processor, **kwargs)
        multi_turn = config.actor_rollout_ref.rollout.multi_turn
        cls.reward_token = str(multi_turn.get("imgsurf_reward_token", "all")).lower()
        if cls.reward_token not in {"all", "outer"}:
            raise ValueError("imgsurf_reward_token must be 'all' or 'outer'")
        cls.max_turn_tokens = int(multi_turn.get("imgsurf_max_turn_tokens", 1024))
        cls.min_final_tokens = int(multi_turn.get("imgsurf_min_final_tokens", 512))
        cls.max_think_summary_tokens = int(multi_turn.get("imgsurf_max_think_summary_tokens", 512))
        cls.final_turn_reserve = cls.min_final_tokens + cls.max_think_summary_tokens + 160
        if cls.final_turn_reserve >= cls.response_length:
            raise ValueError(
                "ImgSurf final-turn reserve must be smaller than rollout.response_length; "
                "increase max_response_length or reduce final/summary token limits."
            )
        cls._install_worker_bridges()

    @classmethod
    def _install_worker_bridges(cls) -> None:
        """Bridge ImgSurf-only rollout metadata and Qwen3-VL M-RoPE.

        The upstream SCAgent worker currently exports neither custom trajectory
        metadata nor Qwen3-VL multimodal inputs.  Installing the small wrappers
        here keeps ImgSurf as a copy-overlay without replacing the large
        upstream worker module.
        """

        # ``@ray.remote`` exposes an ActorClass wrapper.  Patch the underlying
        # class that Ray instantiates rather than the wrapper object.
        ray_metadata = getattr(AgentLoopWorker, "__ray_metadata__", None)
        worker_class = getattr(ray_metadata, "modified_class", AgentLoopWorker)

        if not getattr(worker_class, "_imgsurf_postprocess_bridge", False):
            original_postprocess = worker_class._postprocess

            def imgsurf_postprocess(worker, inputs):
                result = original_postprocess(worker, inputs)
                result.non_tensor_batch["imgsurf_reward_metadata"] = np.array(
                    [
                        (item.multi_modal_data or {}).get("__imgsurf_reward_metadata__", {})
                        for item in inputs
                    ],
                    dtype=object,
                )
                return result

            worker_class._postprocess = imgsurf_postprocess
            worker_class._imgsurf_postprocess_bridge = True

        if not getattr(worker_class, "_imgsurf_qwen3_bridge", False):
            original_run = worker_class._run_agent_loop

            async def imgsurf_run(worker, *args, **kwargs):
                output = await original_run(worker, *args, **kwargs)
                processor_name = worker.processor.image_processor.__class__.__name__
                if "Qwen3VLImageProcessor" not in processor_name:
                    return output

                images = (output.multi_modal_data or {}).get("image", [])
                # Process pixels directly. Re-running the combined processor on
                # an already-expanded token sequence would expand image-pad
                # tokens a second time.
                model_inputs = worker.processor.image_processor(images=images, return_tensors="pt")
                output.multi_modal_inputs = dict(model_inputs)

                from verl.models.transformers.qwen3_vl import get_rope_index

                output.position_ids = get_rope_index(
                    worker.processor,
                    input_ids=output.input_ids.squeeze(0),
                    image_grid_thw=model_inputs.get("image_grid_thw"),
                    video_grid_thw=model_inputs.get("video_grid_thw"),
                    attention_mask=output.attention_mask.squeeze(0),
                ).unsqueeze(0)
                return output

            worker_class._run_agent_loop = imgsurf_run
            worker_class._imgsurf_qwen3_bridge = True

    async def _encode_segment(
        self, messages: list[dict[str, Any]], images: list[Image.Image] | None
    ) -> list[int]:
        raw_text = await self.loop.run_in_executor(
            None,
            lambda: render_imgsurf_chat_prompt(self.processor, messages, self.apply_chat_template_kwargs),
        )
        model_inputs = self.processor(text=[raw_text], images=images or None, return_tensors="pt")
        token_ids = model_inputs.pop("input_ids").squeeze(0).tolist()
        return token_ids[len(self.system_prompt) :]

    @staticmethod
    def _without_images(messages: list[dict[str, Any]]) -> list[dict[str, Any]]:
        result = copy.deepcopy(messages)
        for message in result:
            content = message.get("content")
            if isinstance(content, list):
                message["content"] = [part for part in content if part.get("type") != "image"]
        return result

    async def _append_segment(
        self,
        prompt_ids: list[int],
        response_mask: list[int],
        image_data: list[Image.Image],
        messages: list[dict[str, Any]],
        images: list[Image.Image] | None,
        reserve: int,
        metadata: dict[str, Any],
        allow_image_resize: bool = True,
        allow_text_only: bool = True,
    ) -> bool:
        """Append a scripted v4 segment without exceeding the rollout budget."""

        candidate_images = [image.copy() for image in (images or [])]
        segment_ids: list[int] = []
        for _ in range(7):
            segment_ids = await self._encode_segment(messages, candidate_images)
            if len(response_mask) + len(segment_ids) + reserve <= self.response_length:
                prompt_ids.extend(segment_ids)
                response_mask.extend([0] * len(segment_ids))
                image_data.extend(candidate_images)
                return True
            if not candidate_images or not allow_image_resize:
                break
            candidate_images = [
                image.resize(
                    (max(32, int(image.width * 0.7)), max(32, int(image.height * 0.7))),
                    Image.Resampling.BICUBIC,
                )
                for image in candidate_images
            ]

        # Keeping text is preferable to silently overflowing the context.  A
        # text-only fallback is marked so it can be inspected in rollout logs.
        if not allow_text_only:
            metadata["context_truncated"] = True
            return False
        text_messages = self._without_images(messages)
        segment_ids = await self._encode_segment(text_messages, None)
        if len(response_mask) + len(segment_ids) + reserve <= self.response_length:
            prompt_ids.extend(segment_ids)
            response_mask.extend([0] * len(segment_ids))
            metadata["context_truncated"] = True
            return True
        metadata["context_truncated"] = True
        return False

    async def _generate(
        self,
        request_id: str,
        prompt_ids: list[int],
        response_mask: list[int],
        image_data: list[Image.Image],
        sampling_params: dict[str, Any],
        metrics: dict[str, float],
        gradient_mask: int,
        reserve: int,
    ) -> list[int]:
        available = self.response_length - len(response_mask) - reserve
        if available <= 0:
            return []
        per_turn = min(self.max_turn_tokens, available)
        turn_params = dict(sampling_params)
        turn_params["max_new_tokens"] = per_turn
        with simple_timer("generate_sequences", metrics):
            response_ids = await self.server_manager.generate(
                request_id=request_id,
                prompt_ids=prompt_ids,
                sampling_params=turn_params,
                image_data=image_data,
            )
        response_ids = response_ids[:available]
        prompt_ids.extend(response_ids)
        response_mask.extend([gradient_mask] * len(response_ids))
        return response_ids

    async def _parse_calls(
        self,
        response_ids: list[int],
        tool,
        instance_id: str,
        metadata: dict[str, Any],
        required: bool,
    ) -> tuple[list[dict[str, Any]], str]:
        text = self.tokenizer.decode(response_ids, skip_special_tokens=True)
        textual_attempts = text.count("<tool_call>")
        _, calls = await self.tool_parser.extract_tool_calls(response_ids)
        attempts = max(textual_attempts, len(calls))
        valid_arguments: list[dict[str, Any]] = []
        for call in calls:
            try:
                arguments = json.loads(call.arguments)
                if not isinstance(arguments, dict):
                    continue
                valid, _ = tool.validate_parameters(instance_id, arguments)
                if call.name == "image_zoom_in_tool" and valid:
                    valid_arguments.append(arguments)
            except Exception as exc:
                logger.debug("Ignoring invalid ImgSurf tool call: %s", exc)
                continue

        # A refinement prompt requires a call.  Treat an omitted call as one
        # invalid attempt; an optional initial/final answer may use no tool.
        if required and attempts == 0:
            attempts = 1
        invalid = max(0, attempts - len(valid_arguments))
        metadata["tool_attempts"] += attempts
        metadata["parsed_tool_calls"] += len(valid_arguments)
        metadata["successful_tool_calls"] += len(valid_arguments)
        metadata["invalid_tool_calls"] += invalid
        return valid_arguments, text

    def _think_summary(self, think_blocks: list[str]) -> str:
        summary = "\n---\n".join(block for block in think_blocks[-2:] if block.strip())
        ids = self.tokenizer.encode(summary, add_special_tokens=False)
        if len(ids) > self.max_think_summary_tokens:
            ids = ids[-self.max_think_summary_tokens :]
            summary = self.tokenizer.decode(ids, skip_special_tokens=True)
        return summary

    @rollout_trace_op
    async def run(self, sampling_params: dict[str, Any], **kwargs) -> AgentLoopOutput:
        messages = list(kwargs["raw_prompt"])
        image_data = list(copy.deepcopy(kwargs.get("multi_modal_data", {}).get("image", [])))
        raw_prompt = await self.loop.run_in_executor(
            None,
            lambda: render_imgsurf_chat_prompt(self.processor, messages, self.apply_chat_template_kwargs),
        )
        model_inputs = self.processor(text=[raw_prompt], images=image_data, return_tensors="pt")
        prompt_ids = model_inputs.pop("input_ids").squeeze(0).tolist()
        if len(prompt_ids) > self.prompt_length:
            raise RuntimeError(
                f"ImgSurf prompt has {len(prompt_ids)} tokens, exceeding configured limit {self.prompt_length}."
            )

        response_mask: list[int] = []
        metrics: dict[str, float] = {}
        request_id = uuid4().hex
        tools_kwargs = kwargs.get("tools_kwargs", {})
        tool = self.tools["image_zoom_in_tool"]
        instance_id = None
        think_blocks: list[str] = []
        assistant_turns = 0
        user_turns = 0
        metadata: dict[str, Any] = {
            "tool_attempts": 0,
            "parsed_tool_calls": 0,
            "successful_tool_calls": 0,
            "invalid_tool_calls": 0,
            "converged": False,
            "iterations": 0,
            "expected_max_tool_calls": 1 + tool.max_iter * tool.max_level,
            "reward_token": self.reward_token,
            "context_truncated": False,
        }

        try:
            with simple_timer("tool_calls", metrics):
                instance_id, _ = await tool.create(
                    create_kwargs=tools_kwargs.get("image_zoom_in_tool", {}).get("create_kwargs", {})
                )

            initial_ids = await self._generate(
                request_id,
                prompt_ids,
                response_mask,
                image_data,
                sampling_params,
                metrics,
                gradient_mask=1,
                reserve=self.final_turn_reserve,
            )
            assistant_turns += 1
            initial_calls, initial_text = await self._parse_calls(
                initial_ids, tool, instance_id, metadata, required=False
            )
            already_answered = bool(re.search(r"<answer>\s*.+?\s*</answer>", initial_text, re.DOTALL | re.IGNORECASE))
            first_think = _extract_think(initial_text)
            if first_think:
                think_blocks.append(first_think)

            observation = None
            observation_meta: dict[str, Any] = {}
            if initial_calls and not already_answered:
                with simple_timer("tool_calls", metrics):
                    observation, _, observation_meta = await tool.execute(instance_id, initial_calls[0])

            # Each returned expanded crop becomes the same synthetic zoom-out +
            # local zoom-in exchange used by eval_hrbench_v4.py.
            while observation is not None and not observation_meta.get("done", False):
                crop_images = _images_from_response(observation)
                index = int(observation_meta["index"])
                width, height = observation_meta["display_size"]
                segment = [
                    {
                        "role": "user",
                        "content": (
                            f"Call **image_zoom_out_tool** to output I{index}, whose area is approximately "
                            f"{float(observation_meta['k_level']) ** 2:.6g} times that of the original image."
                        ),
                    },
                    {
                        "role": "assistant",
                        "content": (
                            '<tool_call>{"name":"image_zoom_out_tool","arguments":'
                            + json.dumps(
                                {
                                    "bbox_2d": observation_meta["zoom_out_bbox"],
                                    "index": f"I{index}",
                                },
                                separators=(",", ":"),
                            )
                            + "}</tool_call>"
                        ),
                    },
                    {
                        "role": "user",
                        "content": [
                            {"type": "image"},
                            {
                                "type": "text",
                                "text": build_refine_user_text(
                                    question=observation_meta["question"],
                                    label=observation_meta["label"],
                                    index=index,
                                    model_family=observation_meta["model_family"],
                                    width=width,
                                    height=height,
                                ),
                            },
                        ],
                    },
                ]
                appended = await self._append_segment(
                    prompt_ids,
                    response_mask,
                    image_data,
                    segment,
                    crop_images,
                    self.final_turn_reserve,
                    metadata,
                    allow_image_resize=observation_meta["model_family"] == "qwen3_vl",
                    allow_text_only=False,
                )
                if not appended:
                    with simple_timer("tool_calls", metrics):
                        observation, _, observation_meta = await tool.finalize_current(instance_id)
                    break
                user_turns += 2
                inner_ids = await self._generate(
                    request_id,
                    prompt_ids,
                    response_mask,
                    image_data,
                    sampling_params,
                    metrics,
                    gradient_mask=1 if self.reward_token == "all" else 0,
                    reserve=self.final_turn_reserve,
                )
                assistant_turns += 2  # generated zoom-in plus scripted zoom-out
                calls, inner_text = await self._parse_calls(
                    inner_ids, tool, instance_id, metadata, required=True
                )
                thought = _extract_think(inner_text)
                if thought:
                    think_blocks.append(thought)
                with simple_timer("tool_calls", metrics):
                    if calls:
                        observation, _, observation_meta = await tool.execute(instance_id, calls[0])
                    else:
                        observation, _, observation_meta = await tool.fallback_after_invalid_refinement(instance_id)
                metadata["iterations"] = int(observation_meta.get("iterations", observation_meta.get("iteration", 0)))
                metadata["converged"] = bool(observation_meta.get("converged", False))

            final_images = (
                _images_from_response(observation)
                if not already_answered and observation is not None and observation_meta.get("done")
                else []
            )
            if final_images:
                tool_text = observation.text or "Final refined crop."
                final_segment = [
                    {
                        "role": "user",
                        "content": [
                            {"type": "text", "text": f"<tool_response>\n{tool_text}"},
                            {"type": "image"},
                            {"type": "text", "text": build_final_user_text(self._think_summary(think_blocks))},
                            {"type": "text", "text": "</tool_response>"},
                        ],
                    }
                ]
            elif not already_answered:
                final_segment = [{"role": "user", "content": USER_PROMPT_STEP10_NO_CROPS}]
            else:
                final_segment = []
            appended = False
            if final_segment:
                appended = await self._append_segment(
                    prompt_ids,
                    response_mask,
                    image_data,
                    final_segment,
                    final_images,
                    reserve=self.min_final_tokens,
                    metadata=metadata,
                )
            if appended:
                user_turns += 1
                final_ids = await self._generate(
                    request_id,
                    prompt_ids,
                    response_mask,
                    image_data,
                    sampling_params,
                    metrics,
                    gradient_mask=1,
                    reserve=0,
                )
                assistant_turns += 1
                # Final tool calls are not executed, but malformed JSON still
                # contributes to the parseability reward.
                await self._parse_calls(final_ids, tool, instance_id, metadata, required=False)
        finally:
            if instance_id is not None:
                await tool.release(instance_id)

        split = len(response_mask)
        response_ids = prompt_ids[-split:] if split else []
        initial_prompt_ids = prompt_ids[:-split] if split else prompt_ids
        multi_modal_data = {
            "image": image_data,
            "__imgsurf_reward_metadata__": metadata,
        }
        return AgentLoopOutput(
            prompt_ids=initial_prompt_ids,
            response_ids=response_ids[: self.response_length],
            response_mask=response_mask[: self.response_length],
            multi_modal_data=multi_modal_data,
            num_turns=user_turns + assistant_turns + 1,
            metrics=metrics,
        )
